package com.tek.kata.tennis;

public enum Score {

	// init
	LOVE_ALL,

	// 15 - 0
	FIFTEEN_LOVE,

	// 0 - 15
	LOVE_FIFTEEN,

	FIFTEEN_ALL, 
	THIRTY_LOVE, 
	FORTY_LOVE, 
	LOVE_THIRTY, 
	LOVE_FORTY, 
	FORTY_FIFTEEN,
	FORTY_THIRTY,
	DEUCE, 
	FIFTEEN_THIRTY, 
	THIRTY_ALL, 
	THIRTY_FIFTEEN, 
	FIFTEEN_FORTY, 
	THIRTY_FORTY, 
	ADVANTAGE_SERVER, 
	ADVANTAGE_RECEIVER, 
	GAME_FOR_SERVER,
	GAME_FOR_RECEVER;

	public Score serverWin() {
		return switch (this) {
		case LOVE_ALL -> FIFTEEN_LOVE;
		case FIFTEEN_LOVE -> THIRTY_LOVE;
		case LOVE_FIFTEEN -> FIFTEEN_ALL;
		case FIFTEEN_ALL -> THIRTY_FIFTEEN;
		case THIRTY_LOVE -> FORTY_LOVE;
		case FIFTEEN_THIRTY -> THIRTY_ALL;
		case LOVE_THIRTY -> LOVE_FORTY;
		case LOVE_FORTY -> FIFTEEN_FORTY;
		// server won
		case FORTY_LOVE -> FORTY_FIFTEEN;
		
		case DEUCE -> ADVANTAGE_SERVER;
		case FIFTEEN_FORTY -> THIRTY_FORTY;
		case THIRTY_ALL -> FORTY_THIRTY;
		case THIRTY_FIFTEEN -> FORTY_FIFTEEN;
		case THIRTY_FORTY -> DEUCE;
		case ADVANTAGE_RECEIVER -> DEUCE;
		case GAME_FOR_RECEVER -> GAME_FOR_RECEVER;
		
		case FORTY_FIFTEEN, FORTY_THIRTY, GAME_FOR_SERVER, ADVANTAGE_SERVER -> GAME_FOR_SERVER;
		};
	}
	
	public Score receverWin() {
		return switch (this) {
		case LOVE_ALL -> LOVE_FIFTEEN;
		case FIFTEEN_LOVE -> FIFTEEN_ALL;
		case LOVE_FIFTEEN -> LOVE_THIRTY;
		case FIFTEEN_ALL -> FIFTEEN_THIRTY;
		case THIRTY_LOVE -> THIRTY_FIFTEEN;
		case FORTY_LOVE -> FORTY_FIFTEEN;
		case FORTY_FIFTEEN -> FORTY_THIRTY;
		case FORTY_THIRTY -> DEUCE;
		case LOVE_THIRTY -> LOVE_FORTY;
		case FIFTEEN_THIRTY -> FIFTEEN_FORTY;
		case THIRTY_ALL -> THIRTY_FORTY;
		case THIRTY_FIFTEEN -> THIRTY_ALL;
		case DEUCE -> ADVANTAGE_RECEIVER;
		// recever win
		case FIFTEEN_FORTY -> GAME_FOR_SERVER;
		case LOVE_FORTY -> GAME_FOR_RECEVER;
		case THIRTY_FORTY -> GAME_FOR_RECEVER;
		case ADVANTAGE_SERVER -> DEUCE;
		case ADVANTAGE_RECEIVER -> GAME_FOR_RECEVER;
		case GAME_FOR_RECEVER -> GAME_FOR_RECEVER;
		case GAME_FOR_SERVER -> GAME_FOR_SERVER;
		};
	}
	
	

}